[FEATURE] Weapon/Armor Leveling System (#23)
PlayerEXDirectorsCut/playerex pull request #49
Opened 2024-09-16 03:34 UTC by RedstoneWizard08

Closes #23 
WIP DO NOT MERGE

2024-09-16 11:41 UTC, naomieow requested changes
Please do not include formatting changes in a non-formatting PR.

2024-09-16 11:41 UTC, naomieow commented on build.gradle
Please don't include formatting changed in an non-formatting PR.

2024-09-16 11:41 UTC, naomieow commented on src/main/java/com/bibireden/playerex/mixin/ItemStackMixin.java
> +            assert tag != null;
We shouldn't throw errors during runtime and this also doesn't belong in this PR

2024-09-16 11:41 UTC, naomieow commented on src/main/java/com/bibireden/playerex/mixin/ItemStackMixin.java
> +        if (modifier.getOperation() != AttributeModifier.Operation.ADDITION)
Formatting, and we don't use this form of `if` statement - either use a one line as it was previously or surround with curly braces to improve readabiliy.

2024-09-16 11:41 UTC, naomieow commented on src/main/java/com/bibireden/playerex/mixin/ItemStackMixin.java
Formatting again.

2024-09-16 14:36 UTC, naomieow approved these changes, later dismissed

2024-09-16 14:37 UTC, naomieow commented
Please set up GPG/SSH signing for your commits

2024-09-16 19:26 UTC, RedstoneWizard08 commented
> Please do not include formatting changes in a non-formatting PR.

Ok, will do.

2024-09-16 19:27 UTC, RedstoneWizard08 commented
> Please set up GPG/SSH signing for your commits
I'll work with Poke on that, as I don't know how. I've only ever used git over HTTPS.

2024-09-16 19:30 UTC, naomieow commented
> I'll work with Poke on that, as I don't know how. I've only ever used git over HTTPS.

You can sign your commits with GPG when using HTTPS auth - git just also allows you to sign with SSH as well. I personally use SSH auth and GPG signing. [Here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) is the GitHub documentation for setting up GPG signing.

2024-09-20 18:12 UTC, RedstoneWizard08 commented
btw @naomieow I can prob work on this again tomorrow, I've been busy with homework until now

2024-09-20 18:25 UTC, naomieow commented
> btw @naomieow I can prob work on this again tomorrow, I've been busy with homework until now

awesome, am currently working on getting basic armour levelling working right now

2024-12-13 22:55 UTC, bibi-reden approved these changes
lgtm

2024-12-13 22:56 UTC, merged